---
##############################################################################
#                Data Quality Checks                                         #
##############################################################################
- process.type: Batch
  sink.type: Console
  quality.check.type: QualityCheck
  source:
    source.type: CSV
    source.path: src/main/resources/telco/telco-sample-customer-chum.csv

  #Apply data quality rules on target source
  rules:
    - rule:
        type: NullCheck
        value: gender
        description: Null check failures
    - rule:
        type: PositiveCheck
        value: TotalCharges
        description: positive check failures
    - rule:
        type: EmailCheck
        value: EmailAddress
        description: email address check failures
    - rule:
        type: InRangeCheck
        value: PaymentMethod=ElectronicCheck,MailedCheck,CreditCard,BankTransfer
        description: In range check failures
    - rule:
        type: InRangeCheck
        value: Partner=Yes,No
        description: In range check failures
