---
##############################################################################
#                Data Quality Checks                                         #
##############################################################################
- process.type: Batch
  sink.type: Console
  report.type: Percentage
  source:
    source.type: CSV
    source.path: src/main/resources/telco/telco-sample-customer-chum.csv

  #Telco Data quality rules
  rules:
    - rule:
        type: NullCheck
        value: customerID
        description: Null check failures
    - rule:
        type: InRangeCheck
        value: gender=[Male,Female];PaymentMethod=[Electronic check, Mailed check, Credit card (automatic), Bank transfer (automatic)]
        description: In range check failures
    - rule:
        type: NonNegative
        value: TotalCharges
        description: Negative check failures
    - rule:
        type: Uniqueness
        value: customerID
        description: Uniqueness check failures


#Sample parquet file
- process.type: Batch
  sink.type: Console
  report.type: Count
  source:
    source.type: Parquet
    source.path: src/main/resources/sample/
  # parquet Data quality rules
  rules:
    - rule:
        type: NullCheck
        value: age
        description: Null check failures

