---
##############################################################################
#                Data Quality Checks                                         #
##############################################################################
- process.type: Batch
  sink.type: Console
  quality.check.type: QualityCheck
  source:
    source.type: CSV
    source.path: src/main/resources/telco/telco-sample-customer-chum.csv

  rules:
    - rule:
        type: NullCheck
        value: gender_STRING
        description: Null check failures
    - rule:
        type: PositiveCheck
        value: MonthlyCharges_DOUBLE
        description: positive check failures
    - rule:
        type: EmailCheck
        value: EmailAddress_STRING
        description: email check